steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build image"
    args:
      - "build"
      - "-t"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/pwdmgr-dev-app/password-manager:$SHORT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "Push image"
    args:
      - "push"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/pwdmgr-dev-app/password-manager:$SHORT_SHA"

  - name: "hashicorp/terraform:1.7.5"
    id: "Terraform init"
    entrypoint: "sh"
    dir: "terraform/environments/dev"
    args:
      - "-c"
      - |
        terraform init -input=false

  - name: "hashicorp/terraform:1.7.5"
    id: "Terraform apply"
    entrypoint: "sh"
    dir: "terraform/environments/dev"
    args:
      - "-c"
      - |
        terraform apply -auto-approve -input=false \
          -var="project_id=$PROJECT_ID" \
          -var="app_image=europe-west1-docker.pkg.dev/$PROJECT_ID/pwdmgr-dev-app/password-manager:$SHORT_SHA"

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/pwdmgr-dev-app/password-manager:$SHORT_SHA"

substitutions:
  _TF_ENV: "dev"
