project_id          = "swordmanager"
region              = "europe-west1"
domain_name         = "swordmanager.cloud"
vpc_network         = "swordmanager-vpc"
vpc_subnetwork      = "swordmanager-vpc"
db_private_ip       = "10.132.0.4"
tfstate_bucket_name = "swordmanager-terraform-state"